apiVersion: batch/v1
kind: Job
metadata:
  labels:
    'backstage.io/kubernetes-id': canary-rollout-analysis
  name: hello
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: hello
        image: busybox:1.28
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600 && exit 0']
      restartPolicy: OnFailure
