apiVersion: batch/v1
kind: Job
metadata:
  labels:
    'backstage.io/kubernetes-id': canary-rollout-analysis
  name: hello
spec:
    ttlSecondsAfterFinished: 100
    template:
      spec:
        containers:
        - name: pi
          image: perl
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        restartPolicy: Never
